### ISSUE TITLE
Management of multiple spaces for the declaration of pointers

### ISSUE THREAD

**Issue by Astropilot** [B0sh/asl-extension#1]
Hello,

While trying to open an autosplitter via this extension to benefit from syntax highlighting (thanks a lot for that by the way!) I noticed an omission in the regex of the `pointer-path`. The regex uses the token `\s` for the separation between the type and the name of the pointer but doesn't leave the choice on the number of possible spaces/tabs. For a script that likes to align names this unfortunately blocks syntax highlighting.

https://github.com/B0sh/asl-extension/blob/260e48e24ba63ea1f3cfb73d02653832deac1f40/syntaxes/asl.tmLanguage.json#L65

![image](https://user-images.githubusercontent.com/11898378/102419093-61813480-3fff-11eb-9356-895763acc410.png)

Adding the quantifier `+` to the token `\s` solves the problem:
```regex
\\b(?i)(byte[0-9]+|sbyte|byte|short|ushort|int|uint|long|ulong|float|double|bool|string[0-9]+)\\s+(\\w+)
```

![image](https://user-images.githubusercontent.com/11898378/102420169-cccc0600-4001-11eb-86d9-af75ff01557e.png)

I can make a pull request if necessary :)

Kind regards,
Astropilot

**Comment by B0sh** [comment]
Yo - feel free to make a PR! My asl scripts didn't have this formatting I guess so I never noticed it. Nice find
